spring.data.mongodb.uri=${MONGODB_URI}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# CORS Configuration
app.cors.allowed-origins=http://localhost:3000,http://localhost:3001,http://localhost:5173

# AES Encryption
app.aes.secret=${AES_SECRET}
app.base-url=${APP_BASE_URL:http://localhost:8080}
