spring.data.mongodb.uri=mongodb+srv://24etccs100manthan_db_user:FV6zRF8K0XvcYwgW@cluster0.anwteik.mongodb.net/talentx

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=mjain000289@gmail.com
spring.mail.password=nyjjyadgrlsenftn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT configuration
app.jwt.secret=6767676767676767676767676767676767676767676767676767676767676767
app.jwt.expiration-ms=86400000

# CORS Configuration
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# AES Encryption
app.aes.secret=12345678901234567890123456789012
app.base-url=${APP_BASE_URL:http://localhost:8080}
